name: Issue to RSS

on:
  workflow_dispatch:
  issues:
      types: 
        - opened
        - edited
        - deleted
        - labeled

jobs:
  issue_to_rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master repository
        uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          path: gh-pages

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run script to Issues to RSS
        run: node bin/issues2rss.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ secrets.REPOSITORY }}
          TITLE: ${{ vars.TITLE }}
          DESCRIPTION: ${{ vars.DESCRIPTION }}
          FEED_URL: ${{ vars.FEED_URL }}
          SITE_URL: ${{ vars.SITE_URL }}

      - name: Move rss.xml to gh-pages
        run: |
          mv rss.xml gh-pages/

      - name: Commit and push changes
        run: |
          cd gh-pages
          git config user.name "23784148"
          git config user.email "kenshin726@hotmail.com"
          git add rss.xml
          git commit -m "Update RSS feed with new issue."
          git push origin gh-pages
