name: Issue to RSS

on:
  workflow_dispatch:

jobs:
  issue_to_rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          path: gh-pages

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run script to Issues to RSS
        run: node bin/issues2rss.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ secrets.REPOSITORY }}

      - name: Move rss.xml to gh-pages
        run: |
          mv rss.xml gh-pages/

      - name: Commit and push changes
        run: |
          cd gh-pages
          git add rss.xml
          git commit -m "Update RSS feed with new issue."
          git push origin gh-pages
